Repository sb04-team02/sb04-MoNew-team02, pull requests merged in 2025-09, with the labels that each got.

#178 [알림] (Fix/176) JPA 메서드 네이밍 규칙 위반 등으로 잘못된 NotificationRepository 메서드명 수정 및 대체
  src/main/java/com/sprint/team2/monew/domain/notification/controller/NotificationController.java
  src/main/java/com/sprint/team2/monew/domain/notification/exception/InvalidFormatException.java
  src/main/java/com/sprint/team2/monew/domain/notification/exception/NotificationErrorCode.java
  src/main/java/com/sprint/team2/monew/domain/notification/repository/NotificationRepository.java
  src/main/java/com/sprint/team2/monew/domain/notification/service/NotificationService.java
  src/main/java/com/sprint/team2/monew/domain/notification/service/basic/BasicNotificationsService.java
  src/test/java/com/sprint/team2/monew/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/sprint/team2/monew/domain/notification/service/NotificationServiceTest.java
Labels: Fix

#185 [알림] (Feature/179) 알림 생성 기능 로직 수정 및 이벤트 발행 코드 추가
  src/main/java/com/sprint/team2/monew/domain/article/service/basic/BasicArticleService.java
  src/main/java/com/sprint/team2/monew/domain/like/service/basic/BasicReactionService.java
  src/main/java/com/sprint/team2/monew/domain/notification/event/InterestArticleRegisteredEvent.java
  src/main/java/com/sprint/team2/monew/domain/notification/service/basic/BasicNotificationsService.java
  src/main/java/com/sprint/team2/monew/domain/subscription/repository/SubscriptionRepository.java
  src/test/java/com/sprint/team2/monew/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/sprint/team2/monew/domain/notification/service/NotificationServiceTest.java
Labels: Feat

#257 [CI/CD] (Fix/232) CI 스프링 컨텍스트 로드 실패 문제 해결
  .github/workflows/ci.yml
  src/main/resources/application-dev.yml
Labels: Fix, Refactor

#260 [CI/CD] (Fix/232) 테스트 설정 파일 오버라이딩 추가
  src/test/resources/application-test.yaml
Labels: Fix, Refactor

#276 [CI/CD] (Fix/232) AwsConfig 클래스를 테스트 환경에서 불러오지 않게 어노테이션 추가
  src/main/java/com/sprint/team2/monew/global/config/aws/AwsConfig.java
Labels: Fix

#279 [CI/CD] (Fix/232) ci run 옵션에서 스택트레이스 속성 삭제
  .github/workflows/ci.yml
Labels: Refactor

#285 [CI/CD] (Fix/232) 테스트 환경에서 환경변수 주입받도록 변경
  .github/workflows/ci.yml
  src/main/java/com/sprint/team2/monew/global/config/aws/AwsConfig.java
  src/test/java/com/sprint/team2/monew/global/config/aws/DummyAwsConfig.java
  src/test/resources/application-test.yaml
Labels: Fix, Refactor

#284 [알림] (Refactor/250) 알림 조회 커버 기반 페이지네이션 로직 수정
  src/main/java/com/sprint/team2/monew/domain/notification/controller/NotificationController.java
  src/main/java/com/sprint/team2/monew/domain/notification/repository/NotificationRepository.java
  src/main/java/com/sprint/team2/monew/domain/notification/service/NotificationService.java
  src/main/java/com/sprint/team2/monew/domain/notification/service/basic/BasicNotificationsService.java
  src/test/java/com/sprint/team2/monew/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/sprint/team2/monew/domain/notification/service/NotificationServiceTest.java
Labels: Refactor

#295 [CI/CD] (Fix/255) ci에 디버깅용 옵션 적용
  .github/workflows/ci.yml
Labels: Fix, Refactor

#298 [Test] (Fix/297) H2에 맞게 테스트 스키마 파일 문법 수정
  src/test/resources/test-schema.sql
Labels: Fix, Test, Refactor

#296 [알림] (Fix/290) 레포지토리 메서드 시그니처 오류로 인한 런타임 예외 해결
  src/main/java/com/sprint/team2/monew/domain/notification/controller/NotificationController.java
  src/main/java/com/sprint/team2/monew/domain/notification/repository/NotificationRepository.java
  src/main/java/com/sprint/team2/monew/domain/notification/service/basic/BasicNotificationsService.java
  src/test/java/com/sprint/team2/monew/domain/notification/service/NotificationServiceTest.java
Labels: Fix

#300 [Article] (Fix/299) 메서드명 오타 수정
  src/main/java/com/sprint/team2/monew/domain/article/service/basic/BasicArticleService.java
Labels: Fix

#303 [SQL] (Fix/302) 스키마에 테이블 중복 생성 방지 구문 추가
  src/main/resources/schema.sql
  src/test/resources/test-schema.sql
Labels: Fix, Refactor

#308 [TEST] (Fix/307) 뉴스 기사 정렬 조회 테스트 코드 오류 수정
  src/test/java/com/sprint/team2/monew/domain/article/service/basic/BasicArticleServiceTest.java
Labels: Fix, Test

#324 [CI/CD] (Fix/323) Article 테스트코드 수정
  src/test/java/com/sprint/team2/monew/domain/article/service/basic/BasicArticleServiceTest.java
Labels: Fix, Test

#321 [알림] (Fix/301) MapStruct 매핑 누락된 부분 추가
  src/main/java/com/sprint/team2/monew/domain/notification/mapper/NotificationMapper.java
Labels: Fix

#325 [알림] (Fix/320) 좋아요 관련 이벤트 발행 코드 수정
  src/main/java/com/sprint/team2/monew/domain/like/service/basic/BasicReactionService.java
Labels: Fix

#334 [Base] (Fix/331) WebConfig 메시지 컨버터 코드 변경
  src/main/java/com/sprint/team2/monew/global/config/WebConfig.java
Labels: Fix, Refactor

#344 [알림] (Fix/315) 알림 확인 시 필드명 불일치로 인한 문제
  src/main/java/com/sprint/team2/monew/domain/notification/dto/response/NotificationDto.java
  src/main/java/com/sprint/team2/monew/domain/notification/mapper/NotificationMapper.java
  src/test/java/com/sprint/team2/monew/domain/notification/service/NotificationServiceTest.java
Labels: Fix

#350 [알림] (Fix/349) 확인하지 않은 알림 개수 계산 로직 수정
  src/main/java/com/sprint/team2/monew/domain/notification/repository/NotificationRepository.java
  src/main/java/com/sprint/team2/monew/domain/notification/service/basic/BasicNotificationsService.java
Labels: Fix, Refactor

#383 [알림] (Feature/288) 알림 통합테스트 추가
  src/main/java/com/sprint/team2/monew/domain/notification/repository/NotificationRepository.java
  src/test/java/com/sprint/team2/monew/domain/notification/integration/NotificationIntegrationTest.java
Labels: Test

#396 [알림] (Fix/389) CI 테스트 오류 해결
  src/test/java/com/sprint/team2/monew/domain/notification/integration/NotificationIntegrationTest.java
Labels: Fix
